import type { Chapter, LessonKind, Section, SectionAccent, SectionIcon } from './types'

/** [chapterTitle, chapterSummary, tenLessonTitles] */
type ChapterSeed = [string, string, string[]]

interface SectionSeed {
  title: string
  tagline: string
  description: string
  accent: SectionAccent
  icon: SectionIcon
  chapters: ChapterSeed[]
}

const pad = (value: number) => String(value).padStart(2, '0')

/**
 * The last node of every chapter is a checkpoint; the very last node of a section is its boss
 * project. Nodes explicitly titled "Prática:" are extra reps on an already taught concept.
 */
function kindFor(title: string, lessonIndex: number, isLastChapter: boolean): LessonKind {
  if (lessonIndex === 9) return isLastChapter ? 'boss' : 'checkpoint'
  if (title.startsWith('Prática:')) return 'practice'
  return 'lesson'
}

function buildChapters(sectionId: string, seeds: ChapterSeed[]): Chapter[] {
  return seeds.map(([title, summary, lessons], chapterIndex) => {
    const chapterId = `${sectionId}c${pad(chapterIndex + 1)}`
    const isLastChapter = chapterIndex === seeds.length - 1

    return {
      id: chapterId,
      title,
      summary,
      lessons: lessons.map((lessonTitle, lessonIndex) => ({
        id: `${chapterId}l${pad(lessonIndex + 1)}`,
        title: lessonTitle,
        kind: kindFor(lessonTitle, lessonIndex, isLastChapter),
      })),
    }
  })
}

const seeds: SectionSeed[] = [
  {
    title: 'Fundamentos',
    tagline: 'A base que sustenta todo o resto',
    description:
      'Sintaxe, tipos, operadores, entrada de dados e decisões. Ao final você lê um enunciado e transforma em um programa de console que funciona.',
    accent: 'sky',
    icon: 'sparkles',
    chapters: [
      [
        'Primeiros passos',
        'O que é C#, como um programa nasce e como falar com o console.',
        [
          'C# e .NET: o que é o quê',
          'Anatomia de um programa',
          'Escrevendo na tela com Console.WriteLine',
          'Comentários e código legível',
          'Blocos, chaves e ponto e vírgula',
          'Lendo um erro de compilação',
          'Write vs WriteLine',
          'Sequências de escape',
          'Prática: cartão de visitas',
          'Checkpoint: seu primeiro programa',
        ],
      ],
      [
        'Variáveis e tipos',
        'Guardar informação na memória e escolher o tipo certo para cada dado.',
        [
          'O que é uma variável',
          'Números inteiros com int',
          'Números reais: double e decimal',
          'Verdadeiro ou falso com bool',
          'Um único caractere com char',
          'Texto com string',
          'var e inferência de tipo',
          'Constantes com const',
          'Prática: ficha de personagem',
          'Checkpoint: escolhendo tipos',
        ],
      ],
      [
        'Operadores',
        'Calcular, comparar e combinar condições.',
        [
          'Operadores aritméticos',
          'Divisão inteira e resto com %',
          'Precedência e parênteses',
          'Atribuição composta',
          'Incremento e decremento',
          'Comparando valores',
          'Operadores lógicos && e ||',
          'Negação e curto-circuito',
          'Prática: calculadora de bolso',
          'Checkpoint: expressões',
        ],
      ],
      [
        'Entrada e conversão',
        'Ler dados do usuário e transformar texto em número com segurança.',
        [
          'Lendo com Console.ReadLine',
          'Convertendo texto em int',
          'Convert e as armadilhas do Parse',
          'Validando com int.TryParse',
          'Lendo números decimais',
          'Conversões implícitas',
          'Conversão explícita (cast)',
          'Overflow: quando o número não cabe',
          'Prática: leitor de formulário',
          'Checkpoint: entrada confiável',
        ],
      ],
      [
        'Strings essenciais',
        'Manipular texto: a operação mais comum do dia a dia.',
        [
          'Concatenação de strings',
          'Interpolação com $',
          'Length e acesso por índice',
          'Maiúsculas, minúsculas e Trim',
          'Substring: recortando texto',
          'IndexOf e Contains',
          'Replace e StartsWith',
          'Split e Join',
          'Prática: normalizador de nomes',
          'Checkpoint: manipulando texto',
        ],
      ],
      [
        'Tomando decisões',
        'Fazer o programa escolher caminhos diferentes.',
        [
          'A estrutura if',
          'else: o caminho alternativo',
          'else if e múltiplos caminhos',
          'Condições compostas',
          'if aninhado (e como evitar)',
          'switch clássico',
          'switch como expressão',
          'Padrões relacionais em switch',
          'Prática: classificador de faixas',
          'Checkpoint: fluxo condicional',
        ],
      ],
      [
        'Resolvendo problemas',
        'Aplicar tudo junto: do enunciado ao programa testado.',
        [
          'Lendo o enunciado como um programador',
          'O padrão entrada, processamento, saída',
          'Pensando em casos de borda',
          'Conversor de unidades',
          'Boletim escolar',
          'Simulador de troco',
          'Validador de senha',
          'Calculadora de IMC',
          'Prática: cadastro com validação',
          'Boss: relatório de vendas',
        ],
      ],
    ],
  },
  {
    title: 'Lógica & Repetição',
    tagline: 'Loops, padrões numéricos e raciocínio iterativo',
    description:
      'Domine while, for e controle de fluxo até conseguir simular, acumular e detectar padrões. É aqui que o raciocínio algorítmico começa a aparecer.',
    accent: 'violet',
    icon: 'repeat',
    chapters: [
      [
        'Repetindo com while',
        'O laço mais fundamental e as condições que o param.',
        [
          'Anatomia de um while',
          'Contadores',
          'Acumuladores',
          'Escolhendo a condição de parada',
          'Laço infinito: causa e cura',
          'do-while',
          'Lendo até um valor sentinela',
          'Validação em laço',
          'Prática: somando dígitos',
          'Checkpoint: laços com while',
        ],
      ],
      [
        'Repetindo com for',
        'Quando você sabe quantas vezes vai repetir.',
        [
          'Anatomia de um for',
          'Contando para trás',
          'Ajustando o passo',
          'Várias variáveis de controle',
          'for ou while: como decidir',
          'Somatórios e produtórios',
          'Fatorial iterativo',
          'Fibonacci iterativo',
          'Prática: tabuada completa',
          'Checkpoint: laços com for',
        ],
      ],
      [
        'Controle de fluxo',
        'Interromper, pular e sair de laços com intenção.',
        [
          'break: saindo cedo',
          'continue: pulando uma volta',
          'return antecipado',
          'Laços aninhados',
          'Saindo de laços aninhados',
          'Variáveis de flag',
          'O padrão busca-e-para',
          'Custo de laços aninhados',
          'Prática: primeira ocorrência',
          'Checkpoint: controlando o fluxo',
        ],
      ],
      [
        'Padrões numéricos',
        'Problemas clássicos que treinam raciocínio matemático.',
        [
          'Par, ímpar e divisibilidade',
          'Detectando números primos',
          'Contando divisores',
          'MDC pelo algoritmo de Euclides',
          'MMC a partir do MDC',
          'Invertendo um número',
          'Palíndromo numérico',
          'Conversão para binário',
          'Prática: dígito verificador',
          'Checkpoint: raciocínio numérico',
        ],
      ],
      [
        'Desenhando com loops',
        'Visualizar laços aninhados construindo figuras no console.',
        [
          'Linha de caracteres',
          'Retângulo preenchido',
          'Retângulo vazado',
          'Triângulo alinhado à esquerda',
          'Pirâmide centralizada',
          'Losango',
          'Tabuleiro alternado',
          'Histograma de barras',
          'Prática: régua numerada',
          'Checkpoint: laços aninhados',
        ],
      ],
      [
        'Acumuladores e estatísticas',
        'Extrair informação de uma sequência de valores.',
        [
          'Soma e média',
          'Encontrando o máximo',
          'Encontrando o mínimo',
          'Contagem condicional',
          'Média ponderada',
          'Detectando sequência crescente',
          'Maior sequência repetida',
          'Média móvel',
          'Prática: painel de estatísticas',
          'Checkpoint: agregando dados',
        ],
      ],
      [
        'Problemas com laços',
        'Desafios completos que exigem escolher o laço certo.',
        [
          'FizzBuzz',
          'Troco em moedas',
          'Juros compostos',
          'Adivinhe o número',
          'Sequência de Collatz',
          'Contagem de vogais e consoantes',
          'Simulação de fila de banco',
          'Torneio de pontos',
          'Prática: cronômetro de tarefas',
          'Boss: simulador de caixa',
        ],
      ],
    ],
  },
  {
    title: 'Coleções & Estruturas de Dados',
    tagline: 'Onde os dados moram e por que isso importa',
    description:
      'Arrays, listas, dicionários, conjuntos, filas, pilhas e matrizes. Você vai aprender não só a usar cada estrutura, mas a escolher a certa para cada problema.',
    accent: 'emerald',
    icon: 'layers',
    chapters: [
      [
        'Arrays',
        'A coleção de tamanho fixo, base de tudo.',
        [
          'Declarando um array',
          'Índices e limites',
          'Length e percursos',
          'foreach',
          'Preenchendo a partir da entrada',
          'Copiando arrays',
          'Array.Sort e Array.Reverse',
          'Buscando com Array.IndexOf',
          'Prática: notas da turma',
          'Checkpoint: arrays',
        ],
      ],
      [
        'List<T>',
        'A coleção que cresce junto com o problema.',
        [
          'Criando uma List',
          'Add, Insert e AddRange',
          'Remove, RemoveAt e RemoveAll',
          'Contains e IndexOf',
          'Count e capacidade',
          'Removendo durante o percurso',
          'Ordenando com Sort',
          'Convertendo array e List',
          'Prática: lista de tarefas',
          'Checkpoint: listas',
        ],
      ],
      [
        'Dictionary',
        'Associar chaves a valores e responder perguntas em O(1).',
        [
          'A ideia de chave e valor',
          'Add e o indexador',
          'TryGetValue',
          'ContainsKey e Remove',
          'Percorrendo pares',
          'Contando frequências',
          'Agrupando por chave',
          'Dicionário de listas',
          'Prática: contador de palavras',
          'Checkpoint: dicionários',
        ],
      ],
      [
        'Conjuntos, filas e pilhas',
        'Estruturas com regras próprias de entrada e saída.',
        [
          'HashSet e unicidade',
          'União, interseção e diferença',
          'Removendo duplicados',
          'Queue: primeiro a entrar, primeiro a sair',
          'Stack: último a entrar, primeiro a sair',
          'Balanceamento de parênteses',
          'Avaliando expressão posfixa',
          'Simulando atendimento',
          'Prática: histórico de navegação',
          'Checkpoint: escolhendo a coleção',
        ],
      ],
      [
        'Matrizes',
        'Dados em duas dimensões: grids, tabelas e tabuleiros.',
        [
          'Array bidimensional',
          'Percorrendo linhas e colunas',
          'Somas por linha e por coluna',
          'Diagonais',
          'Transposta',
          'Arrays irregulares (jagged)',
          'Multiplicação de matrizes',
          'Vizinhos em um grid',
          'Prática: campo minado',
          'Checkpoint: dados 2D',
        ],
      ],
      [
        'Tuplas e agrupamentos',
        'Levar mais de um valor junto sem criar uma classe.',
        [
          'Tuplas',
          'Nomeando elementos',
          'Desconstrução',
          'Retornando múltiplos valores',
          'Trocando valores',
          'Ordenando por múltiplos critérios',
          'Chave composta em dicionário',
          'record para dados simples',
          'Prática: ranking com empate',
          'Checkpoint: agrupando dados',
        ],
      ],
      [
        'Escolhendo a estrutura certa',
        'O custo de cada operação e como isso muda a solução.',
        [
          'Custo das operações básicas',
          'Array ou List',
          'List ou Dictionary',
          'HashSet ou List',
          'Quando usar Queue',
          'Quando usar Stack',
          'Memória contra velocidade',
          'Refatorando com a estrutura certa',
          'Prática: carrinho de compras',
          'Boss: agenda de contatos',
        ],
      ],
    ],
  },
  {
    title: 'Métodos & Estilo Funcional',
    tagline: 'Dividir para conquistar, e compor soluções',
    description:
      'Métodos, recursão, delegates, lambdas e LINQ. Você vai sair escrevendo pipelines de dados legíveis em vez de laços gigantes.',
    accent: 'amber',
    icon: 'function',
    chapters: [
      [
        'Métodos',
        'Dar nome a um pedaço de lógica e reutilizá-lo.',
        [
          'Criando seu primeiro método',
          'Parâmetros',
          'Valor de retorno',
          'Métodos void',
          'Métodos chamando métodos',
          'Escolhendo bons nomes',
          'Uma responsabilidade por método',
          'Extraindo método de um bloco grande',
          'Prática: biblioteca de utilidades',
          'Checkpoint: métodos',
        ],
      ],
      [
        'Assinaturas avançadas',
        'Todas as formas de receber e devolver dados.',
        [
          'Sobrecarga de métodos',
          'Parâmetros opcionais',
          'Argumentos nomeados',
          'params: quantidade variável',
          'Passando por referência com ref',
          'Devolvendo com out',
          'in: leitura sem cópia',
          'Retornando tuplas',
          'Prática: parser flexível',
          'Checkpoint: assinaturas',
        ],
      ],
      [
        'Recursão',
        'Resolver um problema em função de si mesmo.',
        [
          'A ideia da recursão',
          'O caso base',
          'Fatorial recursivo',
          'Fibonacci recursivo e seu custo',
          'Somando uma lista',
          'Potência por divisão',
          'Torre de Hanói',
          'A pilha de chamadas',
          'Prática: contagem em árvore',
          'Checkpoint: recursão',
        ],
      ],
      [
        'Delegates e lambdas',
        'Tratar comportamento como dado.',
        [
          'O que é um delegate',
          'Action',
          'Func',
          'Predicate',
          'Expressões lambda',
          'Capturando variáveis (closures)',
          'Passando comportamento como parâmetro',
          'Comparison e ordenação customizada',
          'Prática: pipeline configurável',
          'Checkpoint: comportamento como dado',
        ],
      ],
      [
        'LINQ essencial',
        'As consultas que você vai usar todos os dias.',
        [
          'Where: filtrando',
          'Select: projetando',
          'OrderBy e ThenBy',
          'First, FirstOrDefault e Single',
          'Any e All',
          'Count, Sum e Average',
          'Min, Max e MaxBy',
          'Take, Skip e paginação',
          'Prática: consulta de pedidos',
          'Checkpoint: LINQ básico',
        ],
      ],
      [
        'LINQ avançado',
        'Agrupar, cruzar e achatar dados.',
        [
          'GroupBy',
          'Join',
          'SelectMany',
          'Distinct e DistinctBy',
          'Aggregate',
          'Zip e Chunk',
          'Execução diferida',
          'Sintaxe de consulta',
          'Prática: relatório agrupado',
          'Checkpoint: LINQ avançado',
        ],
      ],
      [
        'Compondo soluções',
        'Transformar dados brutos em respostas.',
        [
          'Pensando em pipeline',
          'Refatorando laços para LINQ',
          'Quando NÃO usar LINQ',
          'Top N com critério de desempate',
          'Filtros combinados dinamicamente',
          'Estatísticas por categoria',
          'Transformando CSV em objetos',
          'Detectando duplicidade em dados',
          'Prática: painel de métricas',
          'Boss: analisador de log',
        ],
      ],
    ],
  },
  {
    title: 'Programação Orientada a Objetos',
    tagline: 'Modelar o problema, não só resolvê-lo',
    description:
      'Classes, encapsulamento, herança, polimorfismo, interfaces e records. O objetivo é sair modelando domínios inteiros com responsabilidades claras.',
    accent: 'rose',
    icon: 'boxes',
    chapters: [
      [
        'Classes e objetos',
        'Criar seus próprios tipos.',
        [
          'Classe e instância',
          'Campos',
          'Métodos de instância',
          'new e referências',
          'this',
          'Construtores',
          'Sobrecarga de construtor',
          'Inicializadores de objeto',
          'Prática: sobrescrevendo ToString',
          'Checkpoint: seus próprios tipos',
        ],
      ],
      [
        'Encapsulamento',
        'Proteger o estado interno de um objeto.',
        [
          'public, private e internal',
          'Propriedades',
          'get e set',
          'Auto-propriedades e valores padrão',
          'Propriedades calculadas',
          'readonly e imutabilidade',
          'Validando no setter',
          'Membros estáticos',
          'Prática: conta com saldo protegido',
          'Checkpoint: encapsulamento',
        ],
      ],
      [
        'Herança',
        'Reaproveitar comportamento sem copiar código.',
        [
          'A ideia de herança',
          'base',
          'Construtores em hierarquia',
          'protected',
          'virtual e override',
          'Escondendo com new',
          'sealed',
          'Profundidade de hierarquia',
          'Prática: hierarquia de funcionários',
          'Checkpoint: herança',
        ],
      ],
      [
        'Polimorfismo',
        'Um mesmo comando, comportamentos diferentes.',
        [
          'Referência do tipo base',
          'Despacho virtual',
          'Classes abstratas',
          'Métodos abstratos',
          'Template method',
          'is e as',
          'Pattern matching por tipo',
          'Coleções polimórficas',
          'Prática: formas geométricas',
          'Checkpoint: polimorfismo',
        ],
      ],
      [
        'Interfaces',
        'Contratos que desacoplam quem usa de quem implementa.',
        [
          'Definindo uma interface',
          'Implementando',
          'Múltiplas interfaces',
          'Interface ou classe abstrata',
          'IComparable e ordenação natural',
          'IEquatable e igualdade',
          'IEnumerable e foreach',
          'Implementação explícita',
          'Prática: plugins de exportação',
          'Checkpoint: interfaces',
        ],
      ],
      [
        'Tipos de valor e records',
        'Escolher entre semântica de valor e de referência.',
        [
          'struct',
          'Semântica de valor',
          'Structs imutáveis',
          'record',
          'record struct',
          'Cópia com with',
          'Igualdade estrutural',
          'enum',
          'Prática: enum com Flags',
          'Checkpoint: valor ou referência',
        ],
      ],
      [
        'Modelando domínios',
        'Do enunciado em português para um modelo de objetos.',
        [
          'Achando os substantivos e os verbos',
          'Distribuindo responsabilidades',
          'Objetos que contêm objetos',
          'Coleções dentro de objetos',
          'Modelando um banco',
          'Modelando uma biblioteca',
          'Modelando um e-commerce',
          'Modelando combate de RPG',
          'Prática: refatorando código procedural',
          'Boss: sistema de reservas',
        ],
      ],
    ],
  },
  {
    title: 'Erros, Testes & Qualidade',
    tagline: 'Código que falha bem e é fácil de mudar',
    description:
      'Exceções, depuração, testes, refatoração e princípios de design. É a seção que separa quem faz funcionar de quem faz durar.',
    accent: 'cyan',
    icon: 'shield',
    chapters: [
      [
        'Exceções',
        'O que fazer quando o inesperado acontece.',
        [
          'O que é uma exceção',
          'try e catch',
          'Exceções mais comuns',
          'Múltiplos blocos catch',
          'finally',
          'using e descarte',
          'Lançando com throw',
          'Relançando sem perder o rastro',
          'Prática: filtros com when',
          'Checkpoint: exceções',
        ],
      ],
      [
        'Falhando de forma robusta',
        'Antecipar o erro em vez de reagir a ele.',
        [
          'Exceções customizadas',
          'Validando argumentos',
          'Guard clauses',
          'O padrão TryParse',
          'Escrevendo seus Try-métodos',
          'O padrão Result',
          'Tipos nullable',
          'Operadores ?. e ??',
          'Prática: ThrowIfNull e validações',
          'Checkpoint: robustez',
        ],
      ],
      [
        'Depuração',
        'Encontrar a causa em vez de adivinhar.',
        [
          'Lendo um stack trace',
          'Interpretando a mensagem de erro',
          'Console como ferramenta de diagnóstico',
          'Debug.Assert',
          'Formulando hipóteses',
          'Bisseção para isolar o bug',
          'Explicando o código em voz alta',
          'Erros de off-by-one',
          'Prática: caçando um bug de estado',
          'Checkpoint: depuração',
        ],
      ],
      [
        'Testes',
        'Provar que funciona, e continuar provando.',
        [
          'Por que testar',
          'Anatomia de um teste',
          'Arrange, Act, Assert',
          'Escolhendo casos de teste',
          'Testando casos de borda',
          'Testando exceções',
          'Testes parametrizados',
          'O que cobertura mede (e o que não)',
          'Prática: primeiro o teste',
          'Checkpoint: testes',
        ],
      ],
      [
        'Código legível',
        'Escrever para a próxima pessoa que vai ler.',
        [
          'Nomes que explicam',
          'Funções curtas',
          'Reduzindo aninhamento',
          'Eliminando números mágicos',
          'Comentários que valem a pena',
          'Retorno antecipado',
          'DRY sem exagero',
          'Convenções do .NET',
          'Prática: limpando um método bagunçado',
          'Checkpoint: legibilidade',
        ],
      ],
      [
        'Refatoração',
        'Melhorar o desenho sem mudar o comportamento.',
        [
          'Extrair método',
          'Extrair classe',
          'Renomear com intenção',
          'Substituir condicional por polimorfismo',
          'Introduzir objeto de parâmetro',
          'Removendo duplicação',
          'Simplificando condições',
          'Dividindo laços que fazem duas coisas',
          'Prática: refatorando com rede de segurança',
          'Checkpoint: refatoração',
        ],
      ],
      [
        'Princípios de design',
        'As heurísticas que guiam decisões difíceis.',
        [
          'Responsabilidade única',
          'Aberto para extensão',
          'Substituição de Liskov',
          'Segregação de interfaces',
          'Inversão de dependência',
          'Composição em vez de herança',
          'Acoplamento e coesão',
          'Injeção de dependência na mão',
          'Prática: identificando code smells',
          'Boss: reescrevendo um módulo legado',
        ],
      ],
    ],
  },
  {
    title: 'Algoritmos & Resolução de Problemas',
    tagline: 'O treino que muda como você pensa',
    description:
      'Complexidade, busca, ordenação, dois ponteiros, janela deslizante, backtracking, programação dinâmica e grafos. A seção mais densa e a que mais desenvolve raciocínio.',
    accent: 'orange',
    icon: 'brain',
    chapters: [
      [
        'Complexidade',
        'Prever o custo antes de escrever o código.',
        [
          'Contando operações',
          'Notação Big-O',
          'O(1), O(n) e O(n²)',
          'O(log n)',
          'Comparando dois algoritmos',
          'Complexidade de espaço',
          'Analisando laços',
          'Analisando recursão',
          'Prática: estimando antes de rodar',
          'Checkpoint: complexidade',
        ],
      ],
      [
        'Busca',
        'Encontrar rápido, com garantias.',
        [
          'Busca linear',
          'Busca com sentinela',
          'Busca binária',
          'Cuidados com os limites',
          'Primeira e última ocorrência',
          'Busca binária na resposta',
          'Busca em matriz ordenada',
          'Erros clássicos de busca binária',
          'Prática: encontrando o ponto de virada',
          'Checkpoint: busca',
        ],
      ],
      [
        'Ordenação',
        'Como os algoritmos clássicos funcionam por dentro.',
        [
          'Bubble sort',
          'Selection sort',
          'Insertion sort',
          'Merge sort',
          'Quick sort',
          'Counting sort',
          'Estabilidade',
          'Ordenando objetos por critério',
          'Prática: comparadores customizados',
          'Checkpoint: ordenação',
        ],
      ],
      [
        'Técnicas de array',
        'Padrões que resolvem famílias inteiras de problemas.',
        [
          'Dois ponteiros',
          'Janela deslizante de tamanho fixo',
          'Janela deslizante variável',
          'Soma de prefixos',
          'Array de diferenças',
          'Subarray de soma máxima (Kadane)',
          'Rotação de array',
          'Particionamento',
          'Prática: mesclando intervalos',
          'Checkpoint: técnicas de array',
        ],
      ],
      [
        'Strings e algoritmos',
        'Problemas de texto que aparecem em toda entrevista.',
        [
          'Contagem de caracteres',
          'Anagramas',
          'Palíndromos',
          'Substring mais longa sem repetição',
          'Compressão RLE',
          'Cifra de César',
          'Tokenização',
          'Distância de edição',
          'Prática: validador de formatos',
          'Checkpoint: strings',
        ],
      ],
      [
        'Backtracking e programação dinâmica',
        'Explorar todas as possibilidades sem desperdício.',
        [
          'Divisão e conquista',
          'Gerando subconjuntos',
          'Gerando permutações',
          'N-Rainhas',
          'Resolvendo um labirinto',
          'Memoização',
          'Programação dinâmica ascendente',
          'Problema da mochila',
          'Prática: troco mínimo',
          'Checkpoint: exploração e DP',
        ],
      ],
      [
        'Grafos e árvores',
        'Modelar relações e navegar por elas.',
        [
          'Representando um grafo',
          'Busca em largura (BFS)',
          'Busca em profundidade (DFS)',
          'Caminho mínimo em grade',
          'Componentes conexos',
          'Detectando ciclos',
          'Ordenação topológica',
          'Árvore binária de busca',
          'Prática: percursos de árvore',
          'Boss: rotas de entrega',
        ],
      ],
    ],
  },
  {
    title: 'C# Avançado & Moderno',
    tagline: 'Os recursos que separam código bom de código elegante',
    description:
      'Genéricos, pattern matching, nullability, iteradores, Span, atributos e os recursos mais recentes da linguagem. Aqui você passa a escrever C# idiomático.',
    accent: 'indigo',
    icon: 'wand',
    chapters: [
      [
        'Genéricos',
        'Escrever uma vez, funcionar com qualquer tipo.',
        [
          'O problema que genéricos resolvem',
          'Métodos genéricos',
          'Classes genéricas',
          'Restrições where',
          'Vários parâmetros de tipo',
          'default e valores genéricos',
          'Genéricos e desempenho',
          'Cache genérico',
          'Prática: fábrica genérica',
          'Checkpoint: genéricos',
        ],
      ],
      [
        'Extensões e APIs fluentes',
        'Estender tipos que você não controla.',
        [
          'Métodos de extensão',
          'Boas práticas de extensão',
          'Estendendo IEnumerable',
          'Estendendo string',
          'Construindo uma API fluente',
          'Sobrecarga de operadores',
          'Indexadores',
          'Conversões implícitas e explícitas',
          'Prática: Deconstruct customizado',
          'Checkpoint: extensões',
        ],
      ],
      [
        'Pattern matching',
        'Descrever a forma do dado em vez de testá-la.',
        [
          'switch como expressão',
          'Padrões de tipo',
          'Padrões relacionais',
          'Padrões lógicos and, or, not',
          'Padrões de propriedade',
          'Padrões posicionais',
          'Padrões de lista',
          'Cláusula when',
          'Prática: máquina de estados',
          'Checkpoint: pattern matching',
        ],
      ],
      [
        'Nullability',
        'Eliminar NullReferenceException por design.',
        [
          'Contexto nullable',
          'Anotações ? em tipos de referência',
          'Análise de fluxo',
          'O operador ! e quando usá-lo',
          'required',
          'init',
          'Nullable de tipos de valor',
          'Padrões de tratamento de null',
          'Prática: eliminando nulls de um módulo',
          'Checkpoint: nullability',
        ],
      ],
      [
        'Iteradores e sequências',
        'Produzir dados sob demanda.',
        [
          'IEnumerable por dentro',
          'yield return',
          'yield break',
          'Avaliação preguiçosa',
          'Sequências infinitas',
          'Escrevendo sua coleção',
          'IEnumerator na mão',
          'Range e Index',
          'Prática: gerador de páginas',
          'Checkpoint: iteradores',
        ],
      ],
      [
        'Memória e desempenho',
        'Entender o custo real do que você escreve.',
        [
          'Stack e heap',
          'Boxing e unboxing',
          'Span<T>',
          'ReadOnlySpan e fatias de string',
          'StringBuilder',
          'struct ou class na prática',
          'Como o GC pensa',
          'Reaproveitando buffers',
          'Prática: medindo antes de otimizar',
          'Checkpoint: desempenho',
        ],
      ],
      [
        'Recursos modernos',
        'O C# de hoje, não o de 2010.',
        [
          'Atributos',
          'Reflection na prática',
          'Atributos customizados',
          'Top-level statements',
          'Global usings',
          'Construtores primários',
          'Expressões de coleção',
          'Membros com corpo de expressão',
          'Prática: modernizando código antigo',
          'Boss: mini biblioteca idiomática',
        ],
      ],
    ],
  },
  {
    title: 'Assíncrono, Concorrência & Dados',
    tagline: 'Fazer várias coisas ao mesmo tempo sem se perder',
    description:
      'async/await, cancelamento, paralelismo, concorrência segura, arquivos, streams e JSON. Tudo que um programa real precisa para conversar com o mundo.',
    accent: 'teal',
    icon: 'zap',
    chapters: [
      [
        'Fundamentos de async',
        'Esperar sem travar.',
        [
          'Bloqueante contra assíncrono',
          'O que é uma Task',
          'async e await',
          'Task<T>',
          'Métodos que retornam Task',
          'async void e por que evitar',
          'Encadeando operações',
          'Task.WhenAll',
          'Prática: Task.WhenAny e corrida',
          'Checkpoint: async',
        ],
      ],
      [
        'Controlando a execução',
        'Cancelar, limitar e acompanhar.',
        [
          'Task.Delay',
          'A ideia de cancelamento cooperativo',
          'CancellationToken',
          'Timeout com token',
          'Relatando progresso',
          'Task.Run e trabalho de CPU',
          'Contexto de sincronização',
          'Erros dentro de async',
          'Prática: operação cancelável',
          'Checkpoint: controle de execução',
        ],
      ],
      [
        'Paralelismo',
        'Usar todos os núcleos quando faz sentido.',
        [
          'Parallel.For',
          'Parallel.ForEach',
          'PLINQ',
          'Overhead de paralelizar',
          'Quando NÃO paralelizar',
          'Agregando resultados em paralelo',
          'Parallel.ForEachAsync',
          'Limitando o grau de paralelismo',
          'Prática: processando lotes',
          'Checkpoint: paralelismo',
        ],
      ],
      [
        'Concorrência segura',
        'Compartilhar estado sem corromper dados.',
        [
          'Condição de corrida',
          'lock',
          'Interlocked',
          'Coleções concorrentes',
          'Imutabilidade como estratégia',
          'SemaphoreSlim',
          'Deadlock',
          'Channel',
          'Prática: produtor e consumidor',
          'Checkpoint: concorrência',
        ],
      ],
      [
        'Arquivos e streams',
        'Ler e escrever dados que sobrevivem ao programa.',
        [
          'Lendo um arquivo de texto',
          'Escrevendo em arquivo',
          'Processando linha a linha',
          'Caminhos com Path',
          'O conceito de Stream',
          'StreamReader e StreamWriter',
          'Dados binários',
          'I/O assíncrono',
          'Prática: importando CSV',
          'Checkpoint: arquivos',
        ],
      ],
      [
        'JSON e serialização',
        'O formato que conecta sistemas.',
        [
          'System.Text.Json',
          'Serializando objetos',
          'Desserializando',
          'JsonSerializerOptions',
          'Nomes de propriedade',
          'Objetos aninhados e listas',
          'JsonDocument para leitura solta',
          'Conversores customizados',
          'Prática: erros comuns de JSON',
          'Checkpoint: serialização',
        ],
      ],
      [
        'Integrando dados',
        'Montar um fluxo de dados de ponta a ponta.',
        [
          'Modelando DTOs',
          'Validando dados de entrada',
          'Mapeando DTO para domínio',
          'Consumindo uma API simulada',
          'Cache em memória',
          'Retentativa com backoff',
          'Paginação',
          'Montando um pipeline ETL',
          'Prática: consolidando fontes',
          'Boss: importador resiliente',
        ],
      ],
    ],
  },
  {
    title: '.NET na Prática',
    tagline: 'APIs, persistência e arquitetura de verdade',
    description:
      'CLI, injeção de dependência, Minimal APIs, EF Core, camadas e qualidade em produção. Termina com um projeto completo, do requisito ao empacotamento.',
    accent: 'fuchsia',
    icon: 'server',
    chapters: [
      [
        'Anatomia de uma aplicação',
        'Como um projeto .NET é montado por dentro.',
        [
          'SDK, runtime e CLI',
          'O arquivo csproj',
          'Pacotes NuGet',
          'Soluções e vários projetos',
          'Configuração em camadas',
          'appsettings e variáveis de ambiente',
          'Ambientes de execução',
          'Logging estruturado',
          'Prática: o host genérico',
          'Checkpoint: anatomia do projeto',
        ],
      ],
      [
        'Injeção de dependência',
        'Montar objetos sem acoplar quem usa a quem cria.',
        [
          'O problema do new espalhado',
          'Registrando serviços',
          'Ciclos de vida: singleton, scoped e transient',
          'Programando contra interfaces',
          'Múltiplas implementações',
          'Fábricas',
          'Options pattern',
          'DI e testabilidade',
          'Prática: anti-padrões de DI',
          'Checkpoint: injeção de dependência',
        ],
      ],
      [
        'Minimal APIs',
        'Expor sua lógica pela web com pouco cerimonial.',
        [
          'Seu primeiro endpoint',
          'Rotas e verbos',
          'Parâmetros de rota e query',
          'Recebendo JSON no corpo',
          'Códigos de status',
          'TypedResults',
          'Validação de requisição',
          'Agrupando rotas',
          'Prática: middleware',
          'Checkpoint: Minimal API',
        ],
      ],
      [
        'Persistência',
        'Guardar dados para além da execução.',
        [
          'Modelando entidades',
          'Repositório em memória',
          'Conceitos de EF Core',
          'DbContext',
          'Consultando com LINQ',
          'Inserindo e atualizando',
          'Migrations',
          'Relacionamentos',
          'Prática: transações',
          'Checkpoint: persistência',
        ],
      ],
      [
        'Arquitetura',
        'Organizar o código para aguentar mudança.',
        [
          'Pensando em camadas',
          'A camada de domínio',
          'A camada de aplicação',
          'A camada de infraestrutura',
          'Portas e adaptadores',
          'DTO contra entidade',
          'Mapeamento entre camadas',
          'Casos de uso',
          'Prática: erros de domínio',
          'Checkpoint: arquitetura',
        ],
      ],
      [
        'Qualidade em produção',
        'O que o código precisa para viver fora da sua máquina.',
        [
          'Testes de integração',
          'Health checks',
          'Observabilidade e métricas',
          'Tratamento global de erros',
          'Segurança básica',
          'Validando configuração na inicialização',
          'Desempenho de API',
          'Versionamento de API',
          'Prática: documentando com OpenAPI',
          'Checkpoint: produção',
        ],
      ],
      [
        'Projeto final',
        'Um sistema completo, construído por etapas.',
        [
          'Levantando requisitos',
          'Modelando o domínio',
          'Implementando as regras de negócio',
          'Serviços de aplicação',
          'Expondo a API',
          'Escrevendo os testes',
          'Refatorando com base no feedback',
          'Revisão de código',
          'Prática: empacotando para publicação',
          'Boss: entrega do projeto final',
        ],
      ],
    ],
  },
]

export const curriculum: Section[] = seeds.map((seed, index) => {
  const id = `s${pad(index + 1)}`
  return {
    id,
    index: index + 1,
    title: seed.title,
    tagline: seed.tagline,
    description: seed.description,
    accent: seed.accent,
    icon: seed.icon,
    chapters: buildChapters(id, seed.chapters),
  }
})

export const sectionById = new Map(curriculum.map((section) => [section.id, section]))

export const allLessonRefs = curriculum.flatMap((section) =>
  section.chapters.flatMap((chapter) =>
    chapter.lessons.map((ref) => ({ section, chapter, ref })),
  ),
)

export function countLessons(section: Section): number {
  return section.chapters.reduce((total, chapter) => total + chapter.lessons.length, 0)
}

export const totalLessonCount = curriculum.reduce(
  (total, section) => total + countLessons(section),
  0,
)
